apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  name: byeworld
spec:
  minReadySeconds: 5
  replicas: 2
  template:
    metadata:
      labels:
        name: byeworld
    spec:
      containers:
      - name: byeworld
        image: quay.io/tamarakaufler/byeworld:master-a000001
        args:
        - -msg=Bye all
        ports:
        - containerPort: 80
